# Generated by Django 3.0.2 on 2020-01-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Characters', '0001_initial'),
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('story', models.TextField(blank=True, default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Places.Place')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stories.Story')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterInStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Characters.Character')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stories.Story')),
            ],
        ),
    ]
