# Generated by Django 3.0.2 on 2020-01-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('Stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeinstory',
            old_name='character',
            new_name='place',
        ),
        migrations.CreateModel(
            name='ItemInStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Items.Item')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stories.Story')),
            ],
        ),
    ]
