# Generated by Django 2.2.1 on 2020-02-12 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0002_storyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
