# Generated by Django 2.2.1 on 2020-02-12 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0003_story_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
