# Generated by Django 2.2.1 on 2020-02-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='character',
            new_name='item',
        ),
    ]
