# Generated by Django 2.2.1 on 2020-02-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20200212_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display',
            field=models.ImageField(default='images/item_displays/default.png', upload_to='images/item_displays'),
        ),
    ]
