# Generated by Django 2.2.1 on 2020-02-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(default='images/region_images/default.png', upload_to='images/region_images'),
        ),
    ]
